version: 1
validation: sovereign
accounts: 
- name: mert
  coins:
  - 2000000000vita
- name: yigit
  coins:
  - 2000000000vita
- name: carol
  coins:
  - 1000000000vita 
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: carol
  coins:
  - 100000vita
genesis:
  app_state:
    staking:
      params:
        bond_denom: vita
validators:
- name: mert
  bonded: 100000000vita
- name: yigit
  bonded: 100000000vita
- name: validator2
  bonded: 200000000vita
- name: validator3
  bonded: 300000000vita