// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vita/gainsharing/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetMechanismRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetMechanismRequest) Reset()         { *m = QueryGetMechanismRequest{} }
func (m *QueryGetMechanismRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMechanismRequest) ProtoMessage()    {}
func (*QueryGetMechanismRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{2}
}
func (m *QueryGetMechanismRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMechanismRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMechanismRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMechanismRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMechanismRequest.Merge(m, src)
}
func (m *QueryGetMechanismRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMechanismRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMechanismRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMechanismRequest proto.InternalMessageInfo

func (m *QueryGetMechanismRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetMechanismResponse struct {
	Mechanism Mechanism `protobuf:"bytes,1,opt,name=Mechanism,proto3" json:"Mechanism"`
}

func (m *QueryGetMechanismResponse) Reset()         { *m = QueryGetMechanismResponse{} }
func (m *QueryGetMechanismResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMechanismResponse) ProtoMessage()    {}
func (*QueryGetMechanismResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{3}
}
func (m *QueryGetMechanismResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMechanismResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMechanismResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMechanismResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMechanismResponse.Merge(m, src)
}
func (m *QueryGetMechanismResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMechanismResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMechanismResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMechanismResponse proto.InternalMessageInfo

func (m *QueryGetMechanismResponse) GetMechanism() Mechanism {
	if m != nil {
		return m.Mechanism
	}
	return Mechanism{}
}

type QueryAllMechanismRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMechanismRequest) Reset()         { *m = QueryAllMechanismRequest{} }
func (m *QueryAllMechanismRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMechanismRequest) ProtoMessage()    {}
func (*QueryAllMechanismRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{4}
}
func (m *QueryAllMechanismRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMechanismRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMechanismRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMechanismRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMechanismRequest.Merge(m, src)
}
func (m *QueryAllMechanismRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMechanismRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMechanismRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMechanismRequest proto.InternalMessageInfo

func (m *QueryAllMechanismRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMechanismResponse struct {
	Mechanism  []Mechanism         `protobuf:"bytes,1,rep,name=Mechanism,proto3" json:"Mechanism"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMechanismResponse) Reset()         { *m = QueryAllMechanismResponse{} }
func (m *QueryAllMechanismResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMechanismResponse) ProtoMessage()    {}
func (*QueryAllMechanismResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{5}
}
func (m *QueryAllMechanismResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMechanismResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMechanismResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMechanismResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMechanismResponse.Merge(m, src)
}
func (m *QueryAllMechanismResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMechanismResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMechanismResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMechanismResponse proto.InternalMessageInfo

func (m *QueryAllMechanismResponse) GetMechanism() []Mechanism {
	if m != nil {
		return m.Mechanism
	}
	return nil
}

func (m *QueryAllMechanismResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPerformanceRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetPerformanceRequest) Reset()         { *m = QueryGetPerformanceRequest{} }
func (m *QueryGetPerformanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPerformanceRequest) ProtoMessage()    {}
func (*QueryGetPerformanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{6}
}
func (m *QueryGetPerformanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPerformanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPerformanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPerformanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPerformanceRequest.Merge(m, src)
}
func (m *QueryGetPerformanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPerformanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPerformanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPerformanceRequest proto.InternalMessageInfo

func (m *QueryGetPerformanceRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetPerformanceResponse struct {
	Performance Performance `protobuf:"bytes,1,opt,name=Performance,proto3" json:"Performance"`
}

func (m *QueryGetPerformanceResponse) Reset()         { *m = QueryGetPerformanceResponse{} }
func (m *QueryGetPerformanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPerformanceResponse) ProtoMessage()    {}
func (*QueryGetPerformanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{7}
}
func (m *QueryGetPerformanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPerformanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPerformanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPerformanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPerformanceResponse.Merge(m, src)
}
func (m *QueryGetPerformanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPerformanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPerformanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPerformanceResponse proto.InternalMessageInfo

func (m *QueryGetPerformanceResponse) GetPerformance() Performance {
	if m != nil {
		return m.Performance
	}
	return Performance{}
}

type QueryAllPerformanceRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPerformanceRequest) Reset()         { *m = QueryAllPerformanceRequest{} }
func (m *QueryAllPerformanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPerformanceRequest) ProtoMessage()    {}
func (*QueryAllPerformanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{8}
}
func (m *QueryAllPerformanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPerformanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPerformanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPerformanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPerformanceRequest.Merge(m, src)
}
func (m *QueryAllPerformanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPerformanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPerformanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPerformanceRequest proto.InternalMessageInfo

func (m *QueryAllPerformanceRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPerformanceResponse struct {
	Performance []Performance       `protobuf:"bytes,1,rep,name=Performance,proto3" json:"Performance"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPerformanceResponse) Reset()         { *m = QueryAllPerformanceResponse{} }
func (m *QueryAllPerformanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPerformanceResponse) ProtoMessage()    {}
func (*QueryAllPerformanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014d18566bbc83d2, []int{9}
}
func (m *QueryAllPerformanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPerformanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPerformanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPerformanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPerformanceResponse.Merge(m, src)
}
func (m *QueryAllPerformanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPerformanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPerformanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPerformanceResponse proto.InternalMessageInfo

func (m *QueryAllPerformanceResponse) GetPerformance() []Performance {
	if m != nil {
		return m.Performance
	}
	return nil
}

func (m *QueryAllPerformanceResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "vita.gainsharing.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "vita.gainsharing.QueryParamsResponse")
	proto.RegisterType((*QueryGetMechanismRequest)(nil), "vita.gainsharing.QueryGetMechanismRequest")
	proto.RegisterType((*QueryGetMechanismResponse)(nil), "vita.gainsharing.QueryGetMechanismResponse")
	proto.RegisterType((*QueryAllMechanismRequest)(nil), "vita.gainsharing.QueryAllMechanismRequest")
	proto.RegisterType((*QueryAllMechanismResponse)(nil), "vita.gainsharing.QueryAllMechanismResponse")
	proto.RegisterType((*QueryGetPerformanceRequest)(nil), "vita.gainsharing.QueryGetPerformanceRequest")
	proto.RegisterType((*QueryGetPerformanceResponse)(nil), "vita.gainsharing.QueryGetPerformanceResponse")
	proto.RegisterType((*QueryAllPerformanceRequest)(nil), "vita.gainsharing.QueryAllPerformanceRequest")
	proto.RegisterType((*QueryAllPerformanceResponse)(nil), "vita.gainsharing.QueryAllPerformanceResponse")
}

func init() { proto.RegisterFile("vita/gainsharing/query.proto", fileDescriptor_014d18566bbc83d2) }

var fileDescriptor_014d18566bbc83d2 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xc7, 0x33, 0x69, 0x1b, 0xe8, 0xf4, 0x47, 0xf9, 0x39, 0xf6, 0x10, 0x37, 0xcd, 0x36, 0x8c,
	0xad, 0x96, 0x18, 0x77, 0x68, 0x3c, 0x7a, 0x90, 0x04, 0xb4, 0x27, 0x21, 0xee, 0x51, 0xbc, 0x4c,
	0x92, 0x71, 0xbb, 0xb0, 0xbb, 0xb3, 0xdd, 0xdd, 0x56, 0x8b, 0x78, 0xf1, 0x2c, 0x22, 0x28, 0xbe,
	0x03, 0xc1, 0x8b, 0xe0, 0xcb, 0xe8, 0x31, 0xe0, 0xc5, 0x93, 0x48, 0x22, 0xf8, 0x36, 0x64, 0x67,
	0x26, 0xc9, 0x6e, 0x77, 0x37, 0x6d, 0xa5, 0x97, 0xb0, 0xcc, 0x7c, 0x9f, 0xe7, 0xf9, 0x3c, 0xff,
	0x26, 0x70, 0xf3, 0xd8, 0x8e, 0x28, 0xb1, 0xa8, 0xed, 0x85, 0x07, 0x34, 0xb0, 0x3d, 0x8b, 0x1c,
	0x1e, 0xb1, 0xe0, 0xc4, 0xf0, 0x03, 0x1e, 0x71, 0xf4, 0x7f, 0x7c, 0x6b, 0x24, 0x6e, 0xb5, 0x6b,
	0xd4, 0xb5, 0x3d, 0x4e, 0xc4, 0xaf, 0x14, 0x69, 0x1b, 0x16, 0xb7, 0xb8, 0xf8, 0x24, 0xf1, 0x97,
	0x3a, 0xdd, 0xb4, 0x38, 0xb7, 0x1c, 0x46, 0xa8, 0x6f, 0x13, 0xea, 0x79, 0x3c, 0xa2, 0x91, 0xcd,
	0xbd, 0x50, 0xdd, 0x36, 0x07, 0x3c, 0x74, 0x79, 0x48, 0xfa, 0x34, 0x64, 0x32, 0x22, 0x39, 0xde,
	0xeb, 0xb3, 0x88, 0xee, 0x11, 0x9f, 0x5a, 0xb6, 0x27, 0xc4, 0x4a, 0x5b, 0xcf, 0x20, 0xfa, 0x34,
	0xa0, 0xee, 0xd4, 0x55, 0x23, 0x73, 0xed, 0xb2, 0xc1, 0x01, 0xf5, 0xec, 0xd0, 0x55, 0x0a, 0x9c,
	0x75, 0xc0, 0x82, 0xe7, 0x3c, 0x70, 0xa9, 0x37, 0x60, 0x52, 0x83, 0x37, 0x20, 0x7a, 0x12, 0x63,
	0xf4, 0x84, 0x6b, 0x93, 0x1d, 0x1e, 0xb1, 0x30, 0xc2, 0x26, 0xbc, 0x9e, 0x3a, 0x0d, 0x7d, 0xee,
	0x85, 0x0c, 0xdd, 0x87, 0x15, 0x89, 0x50, 0x05, 0x0d, 0xb0, 0xbb, 0xd6, 0xae, 0x1a, 0x67, 0xeb,
	0x64, 0x48, 0x8b, 0xee, 0xea, 0xe9, 0xcf, 0xad, 0xd2, 0x97, 0x3f, 0xdf, 0x9a, 0xc0, 0x54, 0x26,
	0xb8, 0x09, 0xab, 0xc2, 0xe7, 0x3e, 0x8b, 0x1e, 0x4f, 0x41, 0x55, 0x3c, 0xb4, 0x0e, 0xcb, 0xf6,
	0x50, 0x38, 0x5d, 0x36, 0xcb, 0xf6, 0x10, 0x3f, 0x83, 0x37, 0x72, 0xb4, 0x8a, 0xe2, 0x01, 0x5c,
	0x9d, 0x1d, 0x2a, 0x90, 0x5a, 0x16, 0x64, 0x26, 0xe9, 0x2e, 0xc7, 0x2c, 0xe6, 0xdc, 0x06, 0xf7,
	0x15, 0x49, 0xc7, 0x71, 0x32, 0x24, 0x8f, 0x20, 0x9c, 0x37, 0x42, 0x79, 0xbf, 0x65, 0xc8, 0xae,
	0x19, 0x71, 0xd7, 0x0c, 0x39, 0x27, 0xaa, 0x6b, 0x46, 0x8f, 0x5a, 0x4c, 0xd9, 0x9a, 0x09, 0x4b,
	0xfc, 0x19, 0xa8, 0x14, 0xd2, 0x41, 0xf2, 0x53, 0x58, 0xba, 0x6c, 0x0a, 0x68, 0x3f, 0x85, 0x59,
	0x16, 0x98, 0xb7, 0xcf, 0xc5, 0x94, 0xd1, 0x53, 0x9c, 0x2d, 0xa8, 0x4d, 0x2b, 0xdd, 0x9b, 0x0f,
	0x47, 0x51, 0x5f, 0x86, 0xb0, 0x96, 0xab, 0x56, 0x69, 0x3d, 0x84, 0x6b, 0x89, 0x63, 0x55, 0xbd,
	0x7a, 0xce, 0x90, 0xcc, 0x45, 0x2a, 0xb5, 0xa4, 0x1d, 0x1e, 0x2a, 0xa6, 0x8e, 0xe3, 0xe4, 0x30,
	0x5d, 0x55, 0x87, 0xbe, 0x02, 0x95, 0xcc, 0xd9, 0x30, 0x45, 0xc9, 0x2c, 0xfd, 0x4b, 0x32, 0x57,
	0xd6, 0xa9, 0xf6, 0x68, 0x05, 0xae, 0x08, 0x5e, 0xf4, 0x02, 0x56, 0xe4, 0x9a, 0xa1, 0xed, 0x2c,
	0x4e, 0x76, 0x9b, 0xb5, 0x9d, 0x73, 0x54, 0x32, 0x18, 0x6e, 0xbc, 0xf9, 0xfe, 0xfb, 0x43, 0x59,
	0x43, 0x55, 0x52, 0xf0, 0xf0, 0xa0, 0x77, 0x20, 0x31, 0xb7, 0xa8, 0x59, 0xe0, 0x36, 0x67, 0xc1,
	0xb5, 0x3b, 0x17, 0xd2, 0x2a, 0x90, 0x5d, 0x01, 0x82, 0x51, 0x83, 0x14, 0x3f, 0x71, 0xe4, 0x95,
	0x3d, 0x7c, 0x8d, 0xde, 0x02, 0xf8, 0xdf, 0xcc, 0xbe, 0xe3, 0x38, 0x85, 0x4c, 0x39, 0xab, 0x5e,
	0xc8, 0x94, 0xb7, 0xb1, 0xf8, 0xa6, 0x60, 0xaa, 0xa3, 0xda, 0x02, 0x26, 0xf4, 0x09, 0xa4, 0x66,
	0x06, 0xb5, 0x8a, 0xb3, 0xce, 0x0e, 0xb6, 0x76, 0xf7, 0x82, 0x6a, 0x45, 0xd4, 0x14, 0x44, 0xdb,
	0x08, 0x93, 0x45, 0xcf, 0xbc, 0xac, 0xd3, 0x47, 0x00, 0xd7, 0x13, 0x3e, 0xe2, 0x4a, 0xb5, 0x8a,
	0xb3, 0xbf, 0x04, 0x5b, 0xfe, 0xee, 0xe0, 0x1d, 0xc1, 0xb6, 0x85, 0xea, 0x0b, 0xd9, 0xba, 0xed,
	0xd3, 0xb1, 0x0e, 0x46, 0x63, 0x1d, 0xfc, 0x1a, 0xeb, 0xe0, 0xfd, 0x44, 0x2f, 0x8d, 0x26, 0x7a,
	0xe9, 0xc7, 0x44, 0x2f, 0x3d, 0xad, 0x0a, 0xbb, 0x97, 0x29, 0xcb, 0xe8, 0xc4, 0x67, 0x61, 0xbf,
	0x22, 0xfe, 0xb7, 0xee, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x21, 0x51, 0xd0, 0xe0, 0xc1, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Mechanism items.
	Mechanism(ctx context.Context, in *QueryGetMechanismRequest, opts ...grpc.CallOption) (*QueryGetMechanismResponse, error)
	MechanismAll(ctx context.Context, in *QueryAllMechanismRequest, opts ...grpc.CallOption) (*QueryAllMechanismResponse, error)
	// Queries a list of Performance items.
	Performance(ctx context.Context, in *QueryGetPerformanceRequest, opts ...grpc.CallOption) (*QueryGetPerformanceResponse, error)
	PerformanceAll(ctx context.Context, in *QueryAllPerformanceRequest, opts ...grpc.CallOption) (*QueryAllPerformanceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/vita.gainsharing.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Mechanism(ctx context.Context, in *QueryGetMechanismRequest, opts ...grpc.CallOption) (*QueryGetMechanismResponse, error) {
	out := new(QueryGetMechanismResponse)
	err := c.cc.Invoke(ctx, "/vita.gainsharing.Query/Mechanism", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MechanismAll(ctx context.Context, in *QueryAllMechanismRequest, opts ...grpc.CallOption) (*QueryAllMechanismResponse, error) {
	out := new(QueryAllMechanismResponse)
	err := c.cc.Invoke(ctx, "/vita.gainsharing.Query/MechanismAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Performance(ctx context.Context, in *QueryGetPerformanceRequest, opts ...grpc.CallOption) (*QueryGetPerformanceResponse, error) {
	out := new(QueryGetPerformanceResponse)
	err := c.cc.Invoke(ctx, "/vita.gainsharing.Query/Performance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PerformanceAll(ctx context.Context, in *QueryAllPerformanceRequest, opts ...grpc.CallOption) (*QueryAllPerformanceResponse, error) {
	out := new(QueryAllPerformanceResponse)
	err := c.cc.Invoke(ctx, "/vita.gainsharing.Query/PerformanceAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Mechanism items.
	Mechanism(context.Context, *QueryGetMechanismRequest) (*QueryGetMechanismResponse, error)
	MechanismAll(context.Context, *QueryAllMechanismRequest) (*QueryAllMechanismResponse, error)
	// Queries a list of Performance items.
	Performance(context.Context, *QueryGetPerformanceRequest) (*QueryGetPerformanceResponse, error)
	PerformanceAll(context.Context, *QueryAllPerformanceRequest) (*QueryAllPerformanceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Mechanism(ctx context.Context, req *QueryGetMechanismRequest) (*QueryGetMechanismResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mechanism not implemented")
}
func (*UnimplementedQueryServer) MechanismAll(ctx context.Context, req *QueryAllMechanismRequest) (*QueryAllMechanismResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MechanismAll not implemented")
}
func (*UnimplementedQueryServer) Performance(ctx context.Context, req *QueryGetPerformanceRequest) (*QueryGetPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Performance not implemented")
}
func (*UnimplementedQueryServer) PerformanceAll(ctx context.Context, req *QueryAllPerformanceRequest) (*QueryAllPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerformanceAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vita.gainsharing.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Mechanism_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMechanismRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Mechanism(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vita.gainsharing.Query/Mechanism",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Mechanism(ctx, req.(*QueryGetMechanismRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MechanismAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMechanismRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MechanismAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vita.gainsharing.Query/MechanismAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MechanismAll(ctx, req.(*QueryAllMechanismRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Performance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Performance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vita.gainsharing.Query/Performance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Performance(ctx, req.(*QueryGetPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PerformanceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PerformanceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vita.gainsharing.Query/PerformanceAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PerformanceAll(ctx, req.(*QueryAllPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vita.gainsharing.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Mechanism",
			Handler:    _Query_Mechanism_Handler,
		},
		{
			MethodName: "MechanismAll",
			Handler:    _Query_MechanismAll_Handler,
		},
		{
			MethodName: "Performance",
			Handler:    _Query_Performance_Handler,
		},
		{
			MethodName: "PerformanceAll",
			Handler:    _Query_PerformanceAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vita/gainsharing/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMechanismRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMechanismRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMechanismRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMechanismResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMechanismResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMechanismResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Mechanism.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMechanismRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMechanismRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMechanismRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMechanismResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMechanismResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMechanismResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Mechanism) > 0 {
		for iNdEx := len(m.Mechanism) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Mechanism[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPerformanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPerformanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPerformanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPerformanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPerformanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPerformanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Performance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPerformanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPerformanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPerformanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPerformanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPerformanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPerformanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Performance) > 0 {
		for iNdEx := len(m.Performance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Performance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMechanismRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetMechanismResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Mechanism.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMechanismRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMechanismResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Mechanism) > 0 {
		for _, e := range m.Mechanism {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPerformanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetPerformanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Performance.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPerformanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPerformanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Performance) > 0 {
		for _, e := range m.Performance {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMechanismRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMechanismRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMechanismRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMechanismResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMechanismResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMechanismResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mechanism", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Mechanism.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMechanismRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMechanismRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMechanismRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMechanismResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMechanismResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMechanismResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mechanism", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mechanism = append(m.Mechanism, Mechanism{})
			if err := m.Mechanism[len(m.Mechanism)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPerformanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPerformanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPerformanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPerformanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPerformanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPerformanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Performance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Performance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPerformanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPerformanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPerformanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPerformanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPerformanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPerformanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Performance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Performance = append(m.Performance, Performance{})
			if err := m.Performance[len(m.Performance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
