// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package gainsharing

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Mechanism               protoreflect.MessageDescriptor
	fd_Mechanism_id            protoreflect.FieldDescriptor
	fd_Mechanism_metrics       protoreflect.FieldDescriptor
	fd_Mechanism_coefficients  protoreflect.FieldDescriptor
	fd_Mechanism_convergeLimit protoreflect.FieldDescriptor
	fd_Mechanism_slope         protoreflect.FieldDescriptor
	fd_Mechanism_creator       protoreflect.FieldDescriptor
)

func init() {
	file_vita_gainsharing_mechanism_proto_init()
	md_Mechanism = File_vita_gainsharing_mechanism_proto.Messages().ByName("Mechanism")
	fd_Mechanism_id = md_Mechanism.Fields().ByName("id")
	fd_Mechanism_metrics = md_Mechanism.Fields().ByName("metrics")
	fd_Mechanism_coefficients = md_Mechanism.Fields().ByName("coefficients")
	fd_Mechanism_convergeLimit = md_Mechanism.Fields().ByName("convergeLimit")
	fd_Mechanism_slope = md_Mechanism.Fields().ByName("slope")
	fd_Mechanism_creator = md_Mechanism.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_Mechanism)(nil)

type fastReflection_Mechanism Mechanism

func (x *Mechanism) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Mechanism)(x)
}

func (x *Mechanism) slowProtoReflect() protoreflect.Message {
	mi := &file_vita_gainsharing_mechanism_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Mechanism_messageType fastReflection_Mechanism_messageType
var _ protoreflect.MessageType = fastReflection_Mechanism_messageType{}

type fastReflection_Mechanism_messageType struct{}

func (x fastReflection_Mechanism_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Mechanism)(nil)
}
func (x fastReflection_Mechanism_messageType) New() protoreflect.Message {
	return new(fastReflection_Mechanism)
}
func (x fastReflection_Mechanism_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Mechanism
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Mechanism) Descriptor() protoreflect.MessageDescriptor {
	return md_Mechanism
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Mechanism) Type() protoreflect.MessageType {
	return _fastReflection_Mechanism_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Mechanism) New() protoreflect.Message {
	return new(fastReflection_Mechanism)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Mechanism) Interface() protoreflect.ProtoMessage {
	return (*Mechanism)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Mechanism) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Mechanism_id, value) {
			return
		}
	}
	if x.Metrics != "" {
		value := protoreflect.ValueOfString(x.Metrics)
		if !f(fd_Mechanism_metrics, value) {
			return
		}
	}
	if x.Coefficients != "" {
		value := protoreflect.ValueOfString(x.Coefficients)
		if !f(fd_Mechanism_coefficients, value) {
			return
		}
	}
	if x.ConvergeLimit != "" {
		value := protoreflect.ValueOfString(x.ConvergeLimit)
		if !f(fd_Mechanism_convergeLimit, value) {
			return
		}
	}
	if x.Slope != "" {
		value := protoreflect.ValueOfString(x.Slope)
		if !f(fd_Mechanism_slope, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Mechanism_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Mechanism) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vita.gainsharing.Mechanism.id":
		return x.Id != uint64(0)
	case "vita.gainsharing.Mechanism.metrics":
		return x.Metrics != ""
	case "vita.gainsharing.Mechanism.coefficients":
		return x.Coefficients != ""
	case "vita.gainsharing.Mechanism.convergeLimit":
		return x.ConvergeLimit != ""
	case "vita.gainsharing.Mechanism.slope":
		return x.Slope != ""
	case "vita.gainsharing.Mechanism.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.gainsharing.Mechanism"))
		}
		panic(fmt.Errorf("message vita.gainsharing.Mechanism does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Mechanism) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vita.gainsharing.Mechanism.id":
		x.Id = uint64(0)
	case "vita.gainsharing.Mechanism.metrics":
		x.Metrics = ""
	case "vita.gainsharing.Mechanism.coefficients":
		x.Coefficients = ""
	case "vita.gainsharing.Mechanism.convergeLimit":
		x.ConvergeLimit = ""
	case "vita.gainsharing.Mechanism.slope":
		x.Slope = ""
	case "vita.gainsharing.Mechanism.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.gainsharing.Mechanism"))
		}
		panic(fmt.Errorf("message vita.gainsharing.Mechanism does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Mechanism) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vita.gainsharing.Mechanism.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "vita.gainsharing.Mechanism.metrics":
		value := x.Metrics
		return protoreflect.ValueOfString(value)
	case "vita.gainsharing.Mechanism.coefficients":
		value := x.Coefficients
		return protoreflect.ValueOfString(value)
	case "vita.gainsharing.Mechanism.convergeLimit":
		value := x.ConvergeLimit
		return protoreflect.ValueOfString(value)
	case "vita.gainsharing.Mechanism.slope":
		value := x.Slope
		return protoreflect.ValueOfString(value)
	case "vita.gainsharing.Mechanism.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.gainsharing.Mechanism"))
		}
		panic(fmt.Errorf("message vita.gainsharing.Mechanism does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Mechanism) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vita.gainsharing.Mechanism.id":
		x.Id = value.Uint()
	case "vita.gainsharing.Mechanism.metrics":
		x.Metrics = value.Interface().(string)
	case "vita.gainsharing.Mechanism.coefficients":
		x.Coefficients = value.Interface().(string)
	case "vita.gainsharing.Mechanism.convergeLimit":
		x.ConvergeLimit = value.Interface().(string)
	case "vita.gainsharing.Mechanism.slope":
		x.Slope = value.Interface().(string)
	case "vita.gainsharing.Mechanism.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.gainsharing.Mechanism"))
		}
		panic(fmt.Errorf("message vita.gainsharing.Mechanism does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Mechanism) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vita.gainsharing.Mechanism.id":
		panic(fmt.Errorf("field id of message vita.gainsharing.Mechanism is not mutable"))
	case "vita.gainsharing.Mechanism.metrics":
		panic(fmt.Errorf("field metrics of message vita.gainsharing.Mechanism is not mutable"))
	case "vita.gainsharing.Mechanism.coefficients":
		panic(fmt.Errorf("field coefficients of message vita.gainsharing.Mechanism is not mutable"))
	case "vita.gainsharing.Mechanism.convergeLimit":
		panic(fmt.Errorf("field convergeLimit of message vita.gainsharing.Mechanism is not mutable"))
	case "vita.gainsharing.Mechanism.slope":
		panic(fmt.Errorf("field slope of message vita.gainsharing.Mechanism is not mutable"))
	case "vita.gainsharing.Mechanism.creator":
		panic(fmt.Errorf("field creator of message vita.gainsharing.Mechanism is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.gainsharing.Mechanism"))
		}
		panic(fmt.Errorf("message vita.gainsharing.Mechanism does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Mechanism) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vita.gainsharing.Mechanism.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vita.gainsharing.Mechanism.metrics":
		return protoreflect.ValueOfString("")
	case "vita.gainsharing.Mechanism.coefficients":
		return protoreflect.ValueOfString("")
	case "vita.gainsharing.Mechanism.convergeLimit":
		return protoreflect.ValueOfString("")
	case "vita.gainsharing.Mechanism.slope":
		return protoreflect.ValueOfString("")
	case "vita.gainsharing.Mechanism.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.gainsharing.Mechanism"))
		}
		panic(fmt.Errorf("message vita.gainsharing.Mechanism does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Mechanism) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vita.gainsharing.Mechanism", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Mechanism) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Mechanism) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Mechanism) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Mechanism) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Mechanism)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Metrics)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Coefficients)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ConvergeLimit)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Slope)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Mechanism)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.Slope) > 0 {
			i -= len(x.Slope)
			copy(dAtA[i:], x.Slope)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Slope)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.ConvergeLimit) > 0 {
			i -= len(x.ConvergeLimit)
			copy(dAtA[i:], x.ConvergeLimit)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ConvergeLimit)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Coefficients) > 0 {
			i -= len(x.Coefficients)
			copy(dAtA[i:], x.Coefficients)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Coefficients)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Metrics) > 0 {
			i -= len(x.Metrics)
			copy(dAtA[i:], x.Metrics)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Metrics)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Mechanism)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Mechanism: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Mechanism: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Metrics = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Coefficients", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Coefficients = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ConvergeLimit", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ConvergeLimit = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Slope", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Slope = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: vita/gainsharing/mechanism.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mechanism struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Metrics       string `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Coefficients  string `protobuf:"bytes,3,opt,name=coefficients,proto3" json:"coefficients,omitempty"`
	ConvergeLimit string `protobuf:"bytes,4,opt,name=convergeLimit,proto3" json:"convergeLimit,omitempty"`
	Slope         string `protobuf:"bytes,5,opt,name=slope,proto3" json:"slope,omitempty"`
	Creator       string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *Mechanism) Reset() {
	*x = Mechanism{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vita_gainsharing_mechanism_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mechanism) ProtoMessage() {}

// Deprecated: Use Mechanism.ProtoReflect.Descriptor instead.
func (*Mechanism) Descriptor() ([]byte, []int) {
	return file_vita_gainsharing_mechanism_proto_rawDescGZIP(), []int{0}
}

func (x *Mechanism) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mechanism) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

func (x *Mechanism) GetCoefficients() string {
	if x != nil {
		return x.Coefficients
	}
	return ""
}

func (x *Mechanism) GetConvergeLimit() string {
	if x != nil {
		return x.ConvergeLimit
	}
	return ""
}

func (x *Mechanism) GetSlope() string {
	if x != nil {
		return x.Slope
	}
	return ""
}

func (x *Mechanism) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_vita_gainsharing_mechanism_proto protoreflect.FileDescriptor

var file_vita_gainsharing_mechanism_proto_rawDesc = []byte{
	0x0a, 0x20, 0x76, 0x69, 0x74, 0x61, 0x2f, 0x67, 0x61, 0x69, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x69,
	0x6e, 0x67, 0x2f, 0x6d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x76, 0x69, 0x74, 0x61, 0x2e, 0x67, 0x61, 0x69, 0x6e, 0x73, 0x68, 0x61,
	0x72, 0x69, 0x6e, 0x67, 0x22, 0xaf, 0x01, 0x0a, 0x09, 0x4d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69,
	0x73, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67,
	0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0xa2, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76,
	0x69, 0x74, 0x61, 0x2e, 0x67, 0x61, 0x69, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x42,
	0x0e, 0x4d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x19, 0x76, 0x69, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x69, 0x74, 0x61,
	0x2f, 0x67, 0x61, 0x69, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0xa2, 0x02, 0x03, 0x56,
	0x47, 0x58, 0xaa, 0x02, 0x10, 0x56, 0x69, 0x74, 0x61, 0x2e, 0x47, 0x61, 0x69, 0x6e, 0x73, 0x68,
	0x61, 0x72, 0x69, 0x6e, 0x67, 0xca, 0x02, 0x10, 0x56, 0x69, 0x74, 0x61, 0x5c, 0x47, 0x61, 0x69,
	0x6e, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0xe2, 0x02, 0x1c, 0x56, 0x69, 0x74, 0x61, 0x5c,
	0x47, 0x61, 0x69, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x56, 0x69, 0x74, 0x61, 0x3a, 0x3a,
	0x47, 0x61, 0x69, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_vita_gainsharing_mechanism_proto_rawDescOnce sync.Once
	file_vita_gainsharing_mechanism_proto_rawDescData = file_vita_gainsharing_mechanism_proto_rawDesc
)

func file_vita_gainsharing_mechanism_proto_rawDescGZIP() []byte {
	file_vita_gainsharing_mechanism_proto_rawDescOnce.Do(func() {
		file_vita_gainsharing_mechanism_proto_rawDescData = protoimpl.X.CompressGZIP(file_vita_gainsharing_mechanism_proto_rawDescData)
	})
	return file_vita_gainsharing_mechanism_proto_rawDescData
}

var file_vita_gainsharing_mechanism_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vita_gainsharing_mechanism_proto_goTypes = []interface{}{
	(*Mechanism)(nil), // 0: vita.gainsharing.Mechanism
}
var file_vita_gainsharing_mechanism_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vita_gainsharing_mechanism_proto_init() }
func file_vita_gainsharing_mechanism_proto_init() {
	if File_vita_gainsharing_mechanism_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vita_gainsharing_mechanism_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mechanism); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vita_gainsharing_mechanism_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vita_gainsharing_mechanism_proto_goTypes,
		DependencyIndexes: file_vita_gainsharing_mechanism_proto_depIdxs,
		MessageInfos:      file_vita_gainsharing_mechanism_proto_msgTypes,
	}.Build()
	File_vita_gainsharing_mechanism_proto = out.File
	file_vita_gainsharing_mechanism_proto_rawDesc = nil
	file_vita_gainsharing_mechanism_proto_goTypes = nil
	file_vita_gainsharing_mechanism_proto_depIdxs = nil
}
