// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vita/gainsharing/query.proto

package gainsharing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName         = "/vita.gainsharing.Query/Params"
	Query_Mechanism_FullMethodName      = "/vita.gainsharing.Query/Mechanism"
	Query_MechanismAll_FullMethodName   = "/vita.gainsharing.Query/MechanismAll"
	Query_Performance_FullMethodName    = "/vita.gainsharing.Query/Performance"
	Query_PerformanceAll_FullMethodName = "/vita.gainsharing.Query/PerformanceAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Mechanism items.
	Mechanism(ctx context.Context, in *QueryGetMechanismRequest, opts ...grpc.CallOption) (*QueryGetMechanismResponse, error)
	MechanismAll(ctx context.Context, in *QueryAllMechanismRequest, opts ...grpc.CallOption) (*QueryAllMechanismResponse, error)
	// Queries a list of Performance items.
	Performance(ctx context.Context, in *QueryGetPerformanceRequest, opts ...grpc.CallOption) (*QueryGetPerformanceResponse, error)
	PerformanceAll(ctx context.Context, in *QueryAllPerformanceRequest, opts ...grpc.CallOption) (*QueryAllPerformanceResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Mechanism(ctx context.Context, in *QueryGetMechanismRequest, opts ...grpc.CallOption) (*QueryGetMechanismResponse, error) {
	out := new(QueryGetMechanismResponse)
	err := c.cc.Invoke(ctx, Query_Mechanism_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MechanismAll(ctx context.Context, in *QueryAllMechanismRequest, opts ...grpc.CallOption) (*QueryAllMechanismResponse, error) {
	out := new(QueryAllMechanismResponse)
	err := c.cc.Invoke(ctx, Query_MechanismAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Performance(ctx context.Context, in *QueryGetPerformanceRequest, opts ...grpc.CallOption) (*QueryGetPerformanceResponse, error) {
	out := new(QueryGetPerformanceResponse)
	err := c.cc.Invoke(ctx, Query_Performance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PerformanceAll(ctx context.Context, in *QueryAllPerformanceRequest, opts ...grpc.CallOption) (*QueryAllPerformanceResponse, error) {
	out := new(QueryAllPerformanceResponse)
	err := c.cc.Invoke(ctx, Query_PerformanceAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Mechanism items.
	Mechanism(context.Context, *QueryGetMechanismRequest) (*QueryGetMechanismResponse, error)
	MechanismAll(context.Context, *QueryAllMechanismRequest) (*QueryAllMechanismResponse, error)
	// Queries a list of Performance items.
	Performance(context.Context, *QueryGetPerformanceRequest) (*QueryGetPerformanceResponse, error)
	PerformanceAll(context.Context, *QueryAllPerformanceRequest) (*QueryAllPerformanceResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Mechanism(context.Context, *QueryGetMechanismRequest) (*QueryGetMechanismResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mechanism not implemented")
}
func (UnimplementedQueryServer) MechanismAll(context.Context, *QueryAllMechanismRequest) (*QueryAllMechanismResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MechanismAll not implemented")
}
func (UnimplementedQueryServer) Performance(context.Context, *QueryGetPerformanceRequest) (*QueryGetPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Performance not implemented")
}
func (UnimplementedQueryServer) PerformanceAll(context.Context, *QueryAllPerformanceRequest) (*QueryAllPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerformanceAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Mechanism_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMechanismRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Mechanism(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Mechanism_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Mechanism(ctx, req.(*QueryGetMechanismRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MechanismAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMechanismRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MechanismAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_MechanismAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MechanismAll(ctx, req.(*QueryAllMechanismRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Performance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Performance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Performance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Performance(ctx, req.(*QueryGetPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PerformanceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PerformanceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PerformanceAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PerformanceAll(ctx, req.(*QueryAllPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vita.gainsharing.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Mechanism",
			Handler:    _Query_Mechanism_Handler,
		},
		{
			MethodName: "MechanismAll",
			Handler:    _Query_MechanismAll_Handler,
		},
		{
			MethodName: "Performance",
			Handler:    _Query_Performance_Handler,
		},
		{
			MethodName: "PerformanceAll",
			Handler:    _Query_PerformanceAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vita/gainsharing/query.proto",
}
