// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package labour

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Activity             protoreflect.MessageDescriptor
	fd_Activity_id          protoreflect.FieldDescriptor
	fd_Activity_worker      protoreflect.FieldDescriptor
	fd_Activity_beginWork   protoreflect.FieldDescriptor
	fd_Activity_finishWork  protoreflect.FieldDescriptor
	fd_Activity_workingTime protoreflect.FieldDescriptor
	fd_Activity_taskId      protoreflect.FieldDescriptor
	fd_Activity_creator     protoreflect.FieldDescriptor
)

func init() {
	file_vita_labour_activity_proto_init()
	md_Activity = File_vita_labour_activity_proto.Messages().ByName("Activity")
	fd_Activity_id = md_Activity.Fields().ByName("id")
	fd_Activity_worker = md_Activity.Fields().ByName("worker")
	fd_Activity_beginWork = md_Activity.Fields().ByName("beginWork")
	fd_Activity_finishWork = md_Activity.Fields().ByName("finishWork")
	fd_Activity_workingTime = md_Activity.Fields().ByName("workingTime")
	fd_Activity_taskId = md_Activity.Fields().ByName("taskId")
	fd_Activity_creator = md_Activity.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_Activity)(nil)

type fastReflection_Activity Activity

func (x *Activity) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Activity)(x)
}

func (x *Activity) slowProtoReflect() protoreflect.Message {
	mi := &file_vita_labour_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Activity_messageType fastReflection_Activity_messageType
var _ protoreflect.MessageType = fastReflection_Activity_messageType{}

type fastReflection_Activity_messageType struct{}

func (x fastReflection_Activity_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Activity)(nil)
}
func (x fastReflection_Activity_messageType) New() protoreflect.Message {
	return new(fastReflection_Activity)
}
func (x fastReflection_Activity_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Activity
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Activity) Descriptor() protoreflect.MessageDescriptor {
	return md_Activity
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Activity) Type() protoreflect.MessageType {
	return _fastReflection_Activity_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Activity) New() protoreflect.Message {
	return new(fastReflection_Activity)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Activity) Interface() protoreflect.ProtoMessage {
	return (*Activity)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Activity) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Activity_id, value) {
			return
		}
	}
	if x.Worker != "" {
		value := protoreflect.ValueOfString(x.Worker)
		if !f(fd_Activity_worker, value) {
			return
		}
	}
	if x.BeginWork != uint64(0) {
		value := protoreflect.ValueOfUint64(x.BeginWork)
		if !f(fd_Activity_beginWork, value) {
			return
		}
	}
	if x.FinishWork != uint64(0) {
		value := protoreflect.ValueOfUint64(x.FinishWork)
		if !f(fd_Activity_finishWork, value) {
			return
		}
	}
	if x.WorkingTime != int32(0) {
		value := protoreflect.ValueOfInt32(x.WorkingTime)
		if !f(fd_Activity_workingTime, value) {
			return
		}
	}
	if x.TaskId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.TaskId)
		if !f(fd_Activity_taskId, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Activity_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Activity) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vita.labour.Activity.id":
		return x.Id != uint64(0)
	case "vita.labour.Activity.worker":
		return x.Worker != ""
	case "vita.labour.Activity.beginWork":
		return x.BeginWork != uint64(0)
	case "vita.labour.Activity.finishWork":
		return x.FinishWork != uint64(0)
	case "vita.labour.Activity.workingTime":
		return x.WorkingTime != int32(0)
	case "vita.labour.Activity.taskId":
		return x.TaskId != uint64(0)
	case "vita.labour.Activity.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.labour.Activity"))
		}
		panic(fmt.Errorf("message vita.labour.Activity does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Activity) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vita.labour.Activity.id":
		x.Id = uint64(0)
	case "vita.labour.Activity.worker":
		x.Worker = ""
	case "vita.labour.Activity.beginWork":
		x.BeginWork = uint64(0)
	case "vita.labour.Activity.finishWork":
		x.FinishWork = uint64(0)
	case "vita.labour.Activity.workingTime":
		x.WorkingTime = int32(0)
	case "vita.labour.Activity.taskId":
		x.TaskId = uint64(0)
	case "vita.labour.Activity.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.labour.Activity"))
		}
		panic(fmt.Errorf("message vita.labour.Activity does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Activity) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vita.labour.Activity.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "vita.labour.Activity.worker":
		value := x.Worker
		return protoreflect.ValueOfString(value)
	case "vita.labour.Activity.beginWork":
		value := x.BeginWork
		return protoreflect.ValueOfUint64(value)
	case "vita.labour.Activity.finishWork":
		value := x.FinishWork
		return protoreflect.ValueOfUint64(value)
	case "vita.labour.Activity.workingTime":
		value := x.WorkingTime
		return protoreflect.ValueOfInt32(value)
	case "vita.labour.Activity.taskId":
		value := x.TaskId
		return protoreflect.ValueOfUint64(value)
	case "vita.labour.Activity.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.labour.Activity"))
		}
		panic(fmt.Errorf("message vita.labour.Activity does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Activity) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vita.labour.Activity.id":
		x.Id = value.Uint()
	case "vita.labour.Activity.worker":
		x.Worker = value.Interface().(string)
	case "vita.labour.Activity.beginWork":
		x.BeginWork = value.Uint()
	case "vita.labour.Activity.finishWork":
		x.FinishWork = value.Uint()
	case "vita.labour.Activity.workingTime":
		x.WorkingTime = int32(value.Int())
	case "vita.labour.Activity.taskId":
		x.TaskId = value.Uint()
	case "vita.labour.Activity.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.labour.Activity"))
		}
		panic(fmt.Errorf("message vita.labour.Activity does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Activity) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vita.labour.Activity.id":
		panic(fmt.Errorf("field id of message vita.labour.Activity is not mutable"))
	case "vita.labour.Activity.worker":
		panic(fmt.Errorf("field worker of message vita.labour.Activity is not mutable"))
	case "vita.labour.Activity.beginWork":
		panic(fmt.Errorf("field beginWork of message vita.labour.Activity is not mutable"))
	case "vita.labour.Activity.finishWork":
		panic(fmt.Errorf("field finishWork of message vita.labour.Activity is not mutable"))
	case "vita.labour.Activity.workingTime":
		panic(fmt.Errorf("field workingTime of message vita.labour.Activity is not mutable"))
	case "vita.labour.Activity.taskId":
		panic(fmt.Errorf("field taskId of message vita.labour.Activity is not mutable"))
	case "vita.labour.Activity.creator":
		panic(fmt.Errorf("field creator of message vita.labour.Activity is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.labour.Activity"))
		}
		panic(fmt.Errorf("message vita.labour.Activity does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Activity) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vita.labour.Activity.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vita.labour.Activity.worker":
		return protoreflect.ValueOfString("")
	case "vita.labour.Activity.beginWork":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vita.labour.Activity.finishWork":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vita.labour.Activity.workingTime":
		return protoreflect.ValueOfInt32(int32(0))
	case "vita.labour.Activity.taskId":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vita.labour.Activity.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vita.labour.Activity"))
		}
		panic(fmt.Errorf("message vita.labour.Activity does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Activity) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vita.labour.Activity", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Activity) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Activity) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Activity) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Activity) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Activity)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Worker)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.BeginWork != 0 {
			n += 1 + runtime.Sov(uint64(x.BeginWork))
		}
		if x.FinishWork != 0 {
			n += 1 + runtime.Sov(uint64(x.FinishWork))
		}
		if x.WorkingTime != 0 {
			n += 1 + runtime.Sov(uint64(x.WorkingTime))
		}
		if x.TaskId != 0 {
			n += 1 + runtime.Sov(uint64(x.TaskId))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Activity)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x3a
		}
		if x.TaskId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TaskId))
			i--
			dAtA[i] = 0x30
		}
		if x.WorkingTime != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.WorkingTime))
			i--
			dAtA[i] = 0x28
		}
		if x.FinishWork != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.FinishWork))
			i--
			dAtA[i] = 0x20
		}
		if x.BeginWork != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BeginWork))
			i--
			dAtA[i] = 0x18
		}
		if len(x.Worker) > 0 {
			i -= len(x.Worker)
			copy(dAtA[i:], x.Worker)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Worker)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Activity)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Activity: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Activity: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Worker = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BeginWork", wireType)
				}
				x.BeginWork = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BeginWork |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FinishWork", wireType)
				}
				x.FinishWork = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.FinishWork |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field WorkingTime", wireType)
				}
				x.WorkingTime = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.WorkingTime |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
				}
				x.TaskId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TaskId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: vita/labour/activity.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Activity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Worker      string `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	BeginWork   uint64 `protobuf:"varint,3,opt,name=beginWork,proto3" json:"beginWork,omitempty"`
	FinishWork  uint64 `protobuf:"varint,4,opt,name=finishWork,proto3" json:"finishWork,omitempty"`
	WorkingTime int32  `protobuf:"varint,5,opt,name=workingTime,proto3" json:"workingTime,omitempty"`
	TaskId      uint64 `protobuf:"varint,6,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Creator     string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *Activity) Reset() {
	*x = Activity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vita_labour_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_vita_labour_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Activity) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Activity) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *Activity) GetBeginWork() uint64 {
	if x != nil {
		return x.BeginWork
	}
	return 0
}

func (x *Activity) GetFinishWork() uint64 {
	if x != nil {
		return x.FinishWork
	}
	return 0
}

func (x *Activity) GetWorkingTime() int32 {
	if x != nil {
		return x.WorkingTime
	}
	return 0
}

func (x *Activity) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Activity) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_vita_labour_activity_proto protoreflect.FileDescriptor

var file_vita_labour_activity_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x69, 0x74, 0x61, 0x2f, 0x6c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0x2f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x76, 0x69,
	0x74, 0x61, 0x2e, 0x6c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0x22, 0xc4, 0x01, 0x0a, 0x08, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x20, 0x0a, 0x0b,
	0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x42, 0x83, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x2e, 0x6c, 0x61,
	0x62, 0x6f, 0x75, 0x72, 0x42, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x14, 0x76, 0x69, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x69, 0x74, 0x61, 0x2f, 0x6c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0xa2, 0x02, 0x03, 0x56, 0x4c,
	0x58, 0xaa, 0x02, 0x0b, 0x56, 0x69, 0x74, 0x61, 0x2e, 0x4c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0xca,
	0x02, 0x0b, 0x56, 0x69, 0x74, 0x61, 0x5c, 0x4c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0xe2, 0x02, 0x17,
	0x56, 0x69, 0x74, 0x61, 0x5c, 0x4c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x56, 0x69, 0x74, 0x61, 0x3a, 0x3a,
	0x4c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vita_labour_activity_proto_rawDescOnce sync.Once
	file_vita_labour_activity_proto_rawDescData = file_vita_labour_activity_proto_rawDesc
)

func file_vita_labour_activity_proto_rawDescGZIP() []byte {
	file_vita_labour_activity_proto_rawDescOnce.Do(func() {
		file_vita_labour_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_vita_labour_activity_proto_rawDescData)
	})
	return file_vita_labour_activity_proto_rawDescData
}

var file_vita_labour_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vita_labour_activity_proto_goTypes = []interface{}{
	(*Activity)(nil), // 0: vita.labour.Activity
}
var file_vita_labour_activity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vita_labour_activity_proto_init() }
func file_vita_labour_activity_proto_init() {
	if File_vita_labour_activity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vita_labour_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vita_labour_activity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vita_labour_activity_proto_goTypes,
		DependencyIndexes: file_vita_labour_activity_proto_depIdxs,
		MessageInfos:      file_vita_labour_activity_proto_msgTypes,
	}.Build()
	File_vita_labour_activity_proto = out.File
	file_vita_labour_activity_proto_rawDesc = nil
	file_vita_labour_activity_proto_goTypes = nil
	file_vita_labour_activity_proto_depIdxs = nil
}
